### ISSUE TITLE
about pretrain Mobilenet_V2

### ISSUE THREAD

**Issue by zssjh** [lushleaf/Network-Pruning-Greedy-Forward-Selection#1]
hello, I have a puzzle when I read the paper and the code.  Do you use the same pretrain Mobilenet_V2 model when comparing with AMC and MeatPruning? Thank you so much !

**Comment by lushleaf** [comment]
Hi, thanks for asking. I am not sure what pretrained model they use (as the baseline model used in their papers seems also different). Our pretrained model seems have 0.2% higher top1 accuracy than the one reported in meta pruning.

**Comment by zssjh** [comment]
@lushleaf Thank you so much!
