### ISSUE TITLE
Undefiend functions and variables

### ISSUE THREAD

**Issue by munanning** [lushleaf/Network-Pruning-Greedy-Forward-Selection#2]
The theory in your paper is interesting, however, I found some error when trying to reproduce it.

First, in the prune.py, the variable 'num_evaluate_large' and the function 'global_imit_loss' is undefined.

Second, in the finetune.py, the whole mobilenetv3 is undefiend.

Waiting for the up-to-date code~

**Comment by lushleaf** [comment]
Hi, thanks very much for the issue! code is updated.

**Comment by munanning** [comment]
Thanks for your rivision.
When I try to simply reproduce it in cifar10, some errors occurs when reseting parameters(after finishing the pruning on layer 2), I think it comse from the unequal numclasses.
I would try to validate your project in Imagenet when having enough time~
