### ISSUE TITLE
minor mistakes

### ISSUE THREAD

**Issue by kargaranamir** [lushleaf/Network-Pruning-Greedy-Forward-Selection#4]
line code 504 at the "mobile2_prune.py" : net_prune(layer)
There is no variable with "layer" name. 

line code 23 at the "mobile2_prune.py": def net_prune(layer_):
There is no use with "layer_". 

line code 22 at the "mobile2_prune.py" : from lib.net_measure import measure_model
There is no net_measure.py at lib folder.

**Comment by lushleaf** [comment]
Thanks for pointing out. Fixed.
