### ISSUE TITLE
Initial top-1/top-5 accuracies diverge from eval accuracies & pruning stagnates

### ISSUE THREAD

**Issue by lcmeng** [lushleaf/Network-Pruning-Greedy-Forward-Selection#5]
Other than the bugs mentioned in the other open issues, the greedy filter pruning doesn't seem to progress at all. Please see the logs below and help/clarify. Thanks.

Command:
`
python ./mobile2_prune.py --lr=1.2e-3 --n_gpu=4 --n_worker=4 --data_root=~/workspace/datasets/ILSVRC2012/ --load_path=./checkpoint/mobilenetv2_1.0-0c6065bc.pth --batch_size=256
`

Output:
`
[16157 16157 16157 16157]
[3, 2, 1, 0]
=> Preparing data..
=> Preparing data..
Using SGD...
weight decay  = 4e-05
=> Start pruning...
Pruning mobilenet on imagenet...
Layer: (2); Init Loss: 18.4774; **Init top1: (0.0781%); Init top5: (0.3746%)**
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
Layer: (2); Batch top1: 0.0000
Cur_neuron/ All neuron 0 96
...
`

However, the evaluation accuracies are
Command:
`python ./mobile2_prune.py --n_gpu=1 --n_worker=1 --data_root=~/workspace/datasets/ILSVRC2012/ --load_path=./checkpoint/mobilenetv2_1.0-0c6065bc.pth`

Output:
`
[16158]
[0]
=> Preparing data..
=> Preparing data..
Using SGD...
weight decay  = 4e-05
=> Start evaluation...
 [================ 391/391 ==============>]  Step: 1s139ms | Tot: 9m31s | Loss: 1.128 | **Acc1: 72.192% | Acc5: 90.534%**
`

**Comment by lushleaf** [comment]
Hello. Thanks for your issue. I am really sorry for a late reply.

The reason is when pruning the first neuron, we initialize all the weight of the neurons to eps (1e-40), but in the previous code, it only screen neurons with weight zero, which causes that no neuron is being updated for the first iteration. This bug has been fixed in the updated version. I am really sorry for the inconvenience.

Some other bugs in the other issues are also fixed.

Best wishes
